title: Getting started with the Raspberry Pi Code Editor - HTML
hero_image: images/banner.png
description: Getting started with the Raspberry Pi Code Editor - HTML
version: 4
listed: true
copyedit: false
last_tested: "2024-02-15"
steps:
  - title: Introduction
  - title: Code Editor homepage
  - title: Your account and projects
  - title: Code Editor tour
  - title: The Code and Preview panels
  - title: Sidebar panel
  - title: What's next?
